name: "Outdated Check Action"
description: "Measures outdated dependencies by major, minor, and patch versions, providing counts and percentages."
branding:
  icon: activity
  color: green
inputs:
  package-manager:
    description: npm or yarn or pnpm
    default: npm
  cwd:
    description: Current working directory
    default: .
outputs:
  total-dependencies-count:
    description: Total number of dependencies
  outdated-dependencies-count:
    description: Count of outdated dependencies
  latest-dependencies-count:
    description: Count of latest dependencies

  outdated-dependencies-percentage:
    description: Percentage of outdated dependencies
  latest-dependencies-percentage:
    description: Percentage of latest dependencies

  outdated-major-dependencies-count:
    description: Total number of outdated major dependencies.
  outdated-minor-dependencies-count:
    description: Total number of outdated minor dependencies.
  outdated-patch-dependencies-count:
    description: Total number of outdated patch dependencies.

  outdated-major-dependencies-percentage:
    description: Percentage of outdated major dependencies.
  outdated-minor-dependencies-percentage:
    description: Percentage of outdated minor dependencies.
  outdated-patch-dependencies-percentage:
    description: Percentage of outdated patch dependencies.
runs:
  using: "node20"
  main: "dist/index.js"
