name: "dogfooding"
on:
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - run: npm ci && npm run build

      - name: run outdate check
        uses: ./
        id: outdate-check
        with:
          cwd: ./

      - name: send metrics to GCP
        run: npm run run-script ./src/scripts/send-metrics-to-gcp.ts
        env:
          TOTAL_DEPENDENCIES_COUNT: ${{ steps.outdate-check.outputs.total-dependencies-count }}

          OUTDATED_DEPENDENCIES_COUNT: ${{ steps.outdate-check.outputs.outdated-dependencies-count }}
          LATEST_DEPENDENCIES_COUNT: ${{ steps.outdate-check.outputs.latest-dependencies-count }}

          OUTDATED_DEPENDENCIES_PERCENTAGE: ${{ steps.outdate-check.outputs.outdated-dependencies-percentage }}
          LATEST_DEPENDENCIES_PERCENTAGE: ${{ steps.outdate-check.outputs.latest-dependencies-percentage }}

          OUTDATED_MAJOR_DEPENDENCIES_COUNT: ${{ steps.outdate-check.outputs.outdated-major-dependencies-count }}
          OUTDATED_MINOR_DEPENDENCIES_COUNT: ${{ steps.outdate-check.outputs.outdated-minor-dependencies-count }}
          OUTDATED_PATCH_DEPENDENCIES_COUNT: ${{ steps.outdate-check.outputs.outdated-patch-dependencies-count }}

          OUTDATED_MAJOR_DEPENDENCIES_PERCENTAGE: ${{ steps.outdate-check.outputs.outdated-major-dependencies-percentage }}
          OUTDATED_MINOR_DEPENDENCIES_PERCENTAGE: ${{ steps.outdate-check.outputs.outdated-minor-dependencies-percentage }}
          OUTDATED_PATCH_DEPENDENCIES_PERCENTAGE: ${{ steps.outdate-check.outputs.outdated-patch-dependencies-percentage }}
