name: "e2e"
on:
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - run: npm install
        working-directory: ./fixtures

      - run: npm ci && npm run build
      - uses: ./
        with:
          cwd: ./fixtures
