name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: salsify/action-detect-and-tag-new-version@v2
        id: tag-new-version
        with:
          version-command: cat ./VERSION
